import type {ExamPayload} from "./exam-types";
import {REFLECTIONS} from "./exam-types";
export async function buildReportPdf(data:ExamPayload){
 const {jsPDF}=await import("jspdf");const doc=new jsPDF({unit:"mm",format:"a4"});const r=data.report!,a=data.attempt;
 const ink=[32,44,66] as const,accent=[50,89,165] as const,muted=[100,112,135] as const;
 const text=(value:string,x:number,y:number,size=10,color:readonly[number,number,number]=ink,bold=false)=>{doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);doc.setTextColor(...color);doc.text(value,x,y)};
 const clean=(s:string)=>s.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g," ");
 const short=(s:string,n=80)=>s.length>n?s.slice(0,n-3)+"...":s;
 doc.setFillColor(244,246,250);doc.rect(0,0,210,297,"F");
 doc.setFillColor(255,255,255);doc.roundedRect(12,12,186,271,4,4,"F");
 text("MYSQL EXAM STUDIO",21,26,10,accent,true);
 text("Your report card",21,40,23,ink,true);
 text(r.pending?"PROVISIONAL | WRITTEN REVIEW PENDING":"COMPLETED | SELF-REVIEWED PRACTICE",21,48,8,muted,true);
 text(short(clean(a.name),60),21,61,14,ink,true);
 text("Student ID: "+(clean(a.studentId)||"Not supplied"),21,69,9,muted);
 text("Class / batch: "+short(clean(a.cohort)||"Not supplied",58),21,76,9,muted);
 text("Date: "+new Date(a.startedAt).toLocaleDateString("en-GB"),133,61,9,muted);
 text("Duration: "+Math.round(((a.submittedAt??a.startedAt)-a.startedAt)/60000)+" / 90 min",133,69,9,muted);
 text("Answered: "+r.answered+" / 65",133,76,9,muted);
 doc.setDrawColor(220,226,237);doc.line(21,83,189,83);
 text(r.total===null?"PENDING":r.total+" / 100",21,99,r.total===null?19:27,accent,true);
 text(r.total===null?"Overall result awaits written review":r.total+"%  |  "+r.grade+"  |  "+(r.passed?"PASS":"NEEDS PRACTICE"),21,108,9,muted);
 text("Automatic: "+r.automatic+" / 50",133,94,10,ink,true);
 text("Written: "+r.written+" / 50",133,102,10,ink,true);
 text(r.pending?r.pending+" written answers pending":"All written marks resolved",133,110,8,muted);
 doc.setFillColor(244,246,250);doc.rect(21,118,168,9,"F");text("SECTION",24,124,8,muted,true);text("MARKS",136,124,8,muted,true);text("STATUS",159,124,8,muted,true);
 r.sections.forEach((s,i)=>{const y=135+i*9;text(s.code+"   "+s.title,24,y,10);text(s.score+" / "+s.max,136,y,10,ink,true);text(s.pending?"Pending":s.code<"E"?"Automatic":"Self-reviewed",159,y,8,muted);doc.setDrawColor(235,238,244);doc.line(21,y+3,189,y+3)});
 text("Learning priorities",21,205,11,ink,true);
 const weak=r.topics.filter(t=>!t.pending&&t.score<t.max).sort((a,b)=>a.score/a.max-b.score/b.max);
 const priorities=weak.length?weak.slice(0,3).map(t=>t.topic+" ("+t.score+"/"+t.max+")").join("  |  "):r.pending?"Complete the written review to reveal your full topic results.":"All assessed topics achieved full marks. Practise explaining each decision.";
 doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(...muted);doc.text(doc.splitTextToSize(priorities,165),21,213);
 const counts=Object.keys(REFLECTIONS).map(key=>key+": "+Object.values(data.answers).filter(a=>a.reflection===key).length).join("   ");
 text("Mistake reflection counts: "+counts,21,230,9,muted);
 const note="A: concept gap  B: wrong type  C: requirement  D: syntax  E: explain why";
 text(note,21,237,8,muted);
 doc.setFontSize(8);doc.text(doc.splitTextToSize("50 marks are automatically scored; 50 use a human marking guide. Written scores are self-reviewed and are not institution-verified. Pass threshold: 50/100. Blank answers receive zero; no negative marking.",165),21,248);
 text("Attempt: "+a.id,21,269,7,muted);
 doc.setProperties({title:"MySQL report card - "+clean(a.name),subject:"MySQL core concepts assessment",creator:"MySQL Exam Studio"});
 return doc;
}
