import type { SqlQuestion, TableSchema } from "./sql-exam-types";

export const SQL_EXAM_NAME = "SQL Coding Assessment — 30 Minutes";
export const SQL_EXAM_DURATION_MINUTES = 30;
export const SQL_EXAM_DURATION_MS = SQL_EXAM_DURATION_MINUTES * 60 * 1000;
export const TOTAL_MARKS = 100;
export const MARKS_PER_QUESTION = 12.5;

export const DB_SCHEMAS: TableSchema[] = [
  {
    name: "customers",
    description: "Contains customer personal details and location.",
    columns: [
      { name: "customer_id", type: "INT", isPrimary: true },
      { name: "customer_name", type: "VARCHAR(100)" },
      { name: "email", type: "VARCHAR(100)" },
      { name: "city", type: "VARCHAR(50)" },
    ],
    sampleData: [
      { customer_id: 1, customer_name: "Ramesh Kumar", email: "ramesh@example.com", city: "Bengaluru" },
      { customer_id: 2, customer_name: "Priya Sharma", email: "priya@example.com", city: "Mumbai" },
      { customer_id: 3, customer_name: "Anita Roy", email: "anita@example.com", city: "Bengaluru" },
      { customer_id: 4, customer_name: "Suresh Patel", email: "suresh@example.com", city: "Delhi" },
      { customer_id: 5, customer_name: "Vikram Singh", email: "vikram@example.com", city: "Bengaluru" },
      { customer_id: 6, customer_name: "Neha Gupta", email: "neha@example.com", city: "Chennai" },
    ],
  },
  {
    name: "products",
    description: "Contains product catalog information, prices, and available stock.",
    columns: [
      { name: "product_id", type: "INT", isPrimary: true },
      { name: "product_name", type: "VARCHAR(100)" },
      { name: "category", type: "VARCHAR(50)" },
      { name: "price", type: "DECIMAL(10,2)" },
      { name: "stock", type: "INT" },
    ],
    sampleData: [
      { product_id: 101, product_name: "Laptop Pro", category: "Electronics", price: 55000.0, stock: 15 },
      { product_id: 102, product_name: "Wireless Mouse", category: "Accessories", price: 800.0, stock: 50 },
      { product_id: 103, product_name: "Mechanical Keyboard", category: "Accessories", price: 3500.0, stock: 25 },
      { product_id: 104, product_name: "Gaming Monitor", category: "Electronics", price: 18000.0, stock: 10 },
      { product_id: 105, product_name: "USB-C Cable", category: "Accessories", price: 450.0, stock: 100 },
      { product_id: 106, product_name: "Smartphone X", category: "Electronics", price: 42000.0, stock: 20 },
    ],
  },
  {
    name: "orders",
    description: "Contains order headers placed by customers.",
    columns: [
      { name: "order_id", type: "INT", isPrimary: true },
      { name: "customer_id", type: "INT", isForeign: true, references: "customers.customer_id" },
      { name: "order_date", type: "DATE" },
      { name: "total_amount", type: "DECIMAL(10,2)" },
      { name: "status", type: "VARCHAR(20)" },
    ],
    sampleData: [
      { order_id: 1001, customer_id: 1, order_date: "2024-01-15", total_amount: 55800.0, status: "Completed" },
      { order_id: 1002, customer_id: 2, order_date: "2024-01-18", total_amount: 3500.0, status: "Completed" },
      { order_id: 1003, customer_id: 1, order_date: "2024-02-01", total_amount: 18000.0, status: "Shipped" },
      { order_id: 1004, customer_id: 3, order_date: "2024-02-10", total_amount: 42450.0, status: "Completed" },
      { order_id: 1005, customer_id: 4, order_date: "2024-02-14", total_amount: 800.0, status: "Pending" },
      { order_id: 1006, customer_id: 5, order_date: "2024-02-20", total_amount: 3500.0, status: "Completed" },
    ],
  },
  {
    name: "order_items",
    description: "Contains detailed line items for each customer order.",
    columns: [
      { name: "order_item_id", type: "INT", isPrimary: true },
      { name: "order_id", type: "INT", isForeign: true, references: "orders.order_id" },
      { name: "product_id", type: "INT", isForeign: true, references: "products.product_id" },
      { name: "quantity", type: "INT" },
      { name: "unit_price", type: "DECIMAL(10,2)" },
    ],
    sampleData: [
      { order_item_id: 1, order_id: 1001, product_id: 101, quantity: 1, unit_price: 55000.0 },
      { order_item_id: 2, order_id: 1001, product_id: 102, quantity: 1, unit_price: 800.0 },
      { order_item_id: 3, order_id: 1002, product_id: 103, quantity: 1, unit_price: 3500.0 },
      { order_item_id: 4, order_id: 1003, product_id: 104, quantity: 1, unit_price: 18000.0 },
      { order_item_id: 5, order_id: 1004, product_id: 106, quantity: 1, unit_price: 42000.0 },
      { order_item_id: 6, order_id: 1004, product_id: 105, quantity: 1, unit_price: 450.0 },
      { order_item_id: 7, order_id: 1005, product_id: 102, quantity: 1, unit_price: 800.0 },
      { order_item_id: 8, order_id: 1006, product_id: 103, quantity: 2, unit_price: 3500.0 },
    ],
  },
  {
    name: "employees",
    description: "Contains employee records, salaries, and reporting structure.",
    columns: [
      { name: "employee_id", type: "INT", isPrimary: true },
      { name: "employee_name", type: "VARCHAR(100)" },
      { name: "department", type: "VARCHAR(50)" },
      { name: "salary", type: "DECIMAL(10,2)" },
      { name: "manager_id", type: "INT", isForeign: true, references: "employees.employee_id" },
    ],
    sampleData: [
      { employee_id: 1, employee_name: "Arjun Reddy", department: "Engineering", salary: 120000.0, manager_id: null },
      { employee_id: 2, employee_name: "Smriti Mandhana", department: "Engineering", salary: 95000.0, manager_id: 1 },
      { employee_id: 3, employee_name: "Kavita Verma", department: "Marketing", salary: 85000.0, manager_id: 1 },
      { employee_id: 4, employee_name: "Rahul Dravid", department: "Sales", salary: 90000.0, manager_id: 1 },
      { employee_id: 5, employee_name: "Sunil Chhetri", department: "Engineering", salary: 75000.0, manager_id: 2 },
    ],
  },
];

export const SQL_QUESTIONS: SqlQuestion[] = [
  {
    id: 1,
    title: "1. Customers from Bengaluru",
    prompt: "Write a MySQL query to display all columns for all customers whose city is 'Bengaluru'.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query below\nSELECT * FROM customers WHERE ...;\n",
    expectedSql: "SELECT * FROM customers WHERE city = 'Bengaluru';",
    category: "Filtering & WHERE Clause",
    explanation: "Use `WHERE city = 'Bengaluru'` to filter rows from the `customers` table where the city column matches 'Bengaluru'.",
  },
  {
    id: 2,
    title: "2. High-Priced Products",
    prompt: "Write a MySQL query to find all products with a price strictly greater than 1000. Display all columns.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query below\nSELECT * FROM products WHERE ...;\n",
    expectedSql: "SELECT * FROM products WHERE price > 1000;",
    category: "Comparison Operators",
    explanation: "Use the `>` comparison operator in the WHERE clause: `WHERE price > 1000` to select products priced above 1000.",
  },
  {
    id: 3,
    title: "3. Insert New Customer Record",
    prompt: "Write a MySQL statement to insert a new customer into the `customers` table with the following details:\n- `customer_id`: 7\n- `customer_name`: 'Kavya Rao'\n- `email`: 'kavya@example.com'\n- `city`: 'Bengaluru'",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your INSERT query below\nINSERT INTO customers (customer_id, customer_name, email, city) VALUES (...);\n",
    expectedSql: "INSERT INTO customers (customer_id, customer_name, email, city) VALUES (7, 'Kavya Rao', 'kavya@example.com', 'Bengaluru');",
    category: "Data Modification (INSERT)",
    isModification: true,
    explanation: "Use the `INSERT INTO table_name (columns...) VALUES (values...)` syntax to insert a single record into the database table.",
  },
  {
    id: 4,
    title: "4. Update Product Stock",
    prompt: "Write a MySQL statement to update the `stock` quantity to 25 for the product with `product_id` 101 ('Laptop Pro').",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your UPDATE query below\nUPDATE products SET ... WHERE ...;\n",
    expectedSql: "UPDATE products SET stock = 25 WHERE product_id = 101;",
    category: "Data Modification (UPDATE)",
    isModification: true,
    explanation: "Use `UPDATE products SET stock = 25 WHERE product_id = 101;` to modify the stock column for the specific product.",
  },
  {
    id: 5,
    title: "5. Customers Without Orders",
    prompt: "Write a MySQL query to find all customers who have never placed an order. Display all customer details.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query using NOT IN or LEFT JOIN below\nSELECT * FROM customers WHERE ...;\n",
    expectedSql: "SELECT * FROM customers WHERE customer_id NOT IN (SELECT customer_id FROM orders);",
    category: "Subqueries & Outer Joins",
    explanation: "You can use a subquery with `NOT IN`: `WHERE customer_id NOT IN (SELECT customer_id FROM orders)` or a `LEFT JOIN` checking `WHERE orders.order_id IS NULL`.",
  },
  {
    id: 6,
    title: "6. Total Spending Per Customer",
    prompt: "Write a MySQL query to show the `customer_id`, `customer_name`, and total order amount (`total_order_amount`) for every customer who has placed orders. Use `JOIN` and `GROUP BY`.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query using JOIN and GROUP BY below\nSELECT c.customer_id, c.customer_name, SUM(o.total_amount) AS total_order_amount\nFROM customers c\nJOIN orders o ON ...\nGROUP BY ...;\n",
    expectedSql: "SELECT c.customer_id, c.customer_name, SUM(o.total_amount) AS total_order_amount FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id, c.customer_name;",
    category: "JOINS & Aggregations",
    explanation: "Join `customers` with `orders` on `customer_id`, calculate `SUM(orders.total_amount)`, and group by `c.customer_id` and `c.customer_name`.",
  },
  {
    id: 7,
    title: "7. Second Highest Employee Salary",
    prompt: "Write a MySQL query to find the second highest employee salary from the `employees` table. Alias the output column as `second_highest_salary`.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query below\nSELECT MAX(salary) AS second_highest_salary FROM employees WHERE ...;\n",
    expectedSql: "SELECT MAX(salary) AS second_highest_salary FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);",
    category: "Subqueries & Advanced Aggregates",
    explanation: "Use `SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);` or `SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 1;`.",
  },
  {
    id: 8,
    title: "8. Top 3 Products by Quantity Sold",
    prompt: "Write a MySQL query to find the top 3 products by total quantity sold across all orders. Display `product_id`, `product_name`, and `total_quantity` (aliased as `total_quantity`), ordered by total quantity descending.",
    points: MARKS_PER_QUESTION,
    initialCode: "-- Write your query using JOIN, GROUP BY, ORDER BY, and LIMIT below\nSELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity\nFROM products p\nJOIN order_items oi ON ...\nGROUP BY ...\nORDER BY ...\nLIMIT 3;\n",
    expectedSql: "SELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.product_name ORDER BY total_quantity DESC LIMIT 3;",
    category: "Multi-Table Aggregation & Sorting",
    explanation: "Join `products` and `order_items` on `product_id`, group by product, calculate `SUM(quantity)`, order by `total_quantity DESC`, and limit to 3 rows.",
  },
];
