import {createFileRoute} from "@tanstack/react-router";
import {useCallback,useEffect,useState} from "react";
import {ArrowRight,ArrowUpRight,DownloadSimple,Printer,FileText,CheckCircle,Target,ArrowCounterClockwise,BookOpen,WarningCircle} from "@phosphor-icons/react";
import {Shell,ErrorBox,Loading,useQueryId} from "@/components/exam-shell";
import {api,attemptUrl,dateLabel,durationLabel} from "@/lib/exam-client";
import {REFLECTIONS,SECTION_DEFINITIONS} from "@/lib/exam-types";
import type {Attempt,ExamPayload,Question} from "@/lib/exam-types";
export const Route=createFileRoute("/reports")({head:()=>({meta:[{title:"Report cards | MySQL Exam Studio"},{name:"robots",content:"noindex, nofollow"}],links:[{rel:"canonical",href:"https://mysql-exam-studio.higgsfield.app/reports"}]}),component:Reports});
function answerText(q:Question,value:string){if(!value.trim())return "Not answered";if(q.kind==="mcq"||q.kind==="match"){const text=q.options?.[value.charCodeAt(0)-65];return text?value+". "+text:value}return value}
function Reports(){
 const id=useQueryId();const [data,setData]=useState<ExamPayload|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[section,setSection]=useState("all"),[busy,setBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false);
 const load=useCallback(async()=>{if(id===null)return;setLoading(true);setError("");try{if(id){const result=await api<ExamPayload>(undefined,id);if(result.attempt.status==="active"){window.location.replace(attemptUrl(id,"active"));return}setData(result)}else{const result=await api<{attempts:Attempt[]}>();setAttempts(result.attempts)}}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[id]);
 useEffect(()=>{void load()},[load]);
 async function update(body:unknown){setBusy(true);setError("");try{setData(await api<ExamPayload>(body))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function download(){if(!data)return;setPdfBusy(true);try{const {buildReportPdf}=await import("@/lib/report-pdf");const doc=await buildReportPdf(data);doc.save("MySQL-Report-"+data.attempt.name.replace(/[^a-z0-9]+/gi,"-")+"-"+data.attempt.id.slice(0,8)+".pdf")}catch{setError("The PDF could not be created. Try Print / Save PDF instead.")}finally{setPdfBusy(false)}}
 const r=data?.report,a=data?.attempt;
 const reviewQuestions=data?.questions.filter(q=>(section==="all"||q.section===section)&&(filter==="all"||filter==="missed"&&(data.feedback?.[q.id].mark??q.points)<q.points||filter==="pending"&&data.feedback?.[q.id].mark===null||filter==="flagged"&&data.answers[q.id]?.flagged))??[];
 const weak=r?.topics.filter(t=>!t.pending&&t.score<t.max).sort((a,b)=>a.score/a.max-b.score/b.max)??[];
 return <Shell active="reports"><main className="report-page content-wrap">
 {loading?<Loading label="Loading your report cards"/>:<>
 {error&&<ErrorBox message={error} retry={()=>void load()}/>}
 {!data?<><div className="page-title"><span className="eyebrow">YOUR LEARNING RECORD</span><h1>Progress, on the record.</h1><p>Revisit a result. Review your thinking. Take the next step.</p></div>{attempts.length?<div className="history-list">{attempts.map(a=><a className="history-row" href={attemptUrl(a.id,a.status)} key={a.id}><FileText size={27}/><div><strong>{a.name}</strong><small>{dateLabel(a.startedAt)} · {a.answered}/65 answered</small></div><span>{a.status==="active"?"Continue exam":a.pending?"Written review pending":a.automatic+a.written+" / 100"}</span><ArrowUpRight size={21}/></a>)}</div>:<div className="empty-state"><FileText size={48}/><h2>Your first report starts here.</h2><p>Complete an exam to see your score, section breakdown, and answer review.</p><a href="/#begin">Start an attempt <ArrowRight size={18}/></a></div>}</>:r&&a&&<>
 <div className="report-heading"><div><span className="eyebrow">MYSQL CORE CONCEPTS</span><h1>Your skills, in focus.</h1><p>{r.pending?"Your automatic score is ready. Review written answers to complete your report.":"Your assessment is complete. Use the answer review to plan what comes next."}</p></div><div className="report-actions no-print"><button className="download-report" onClick={()=>void download()} disabled={pdfBusy}><DownloadSimple size={20}/>{pdfBusy?"Creating PDF...":"Download report"}</button><button className="print-report" onClick={()=>window.print()}><Printer size={19}/>Print / Save PDF</button></div></div>
 <section className="result-card"><div className="result-identity"><div><strong>{a.name}</strong><span>{[a.studentId,a.cohort].filter(Boolean).join(" · ")||"Personal practice attempt"}</span></div><div><span>{dateLabel(a.startedAt)}</span><span>{durationLabel(a.startedAt,a.submittedAt??a.startedAt)} · {r.answered}/65 answered</span></div></div>
 <div className="result-main"><div className="score-display"><div className="score-ring" style={{"--score":(r.total??r.automatic)/ (r.total===null?50:100)*100+"%"} as React.CSSProperties}><div><strong>{r.total??r.automatic}</strong><span>out of {r.total===null?50:100}</span></div></div><div className="score-caption"><h2>{r.pending?"Automatic score":r.passed?"Keep building on it.":"A clear place to start."}</h2><p>{r.pending?"Overall grade pending":r.grade+" · "+r.percentage+"% · "+(r.passed?"Pass":"Needs practice")}</p><span className="status-label">{r.pending?"Provisional result":"Self-reviewed practice"}</span></div></div>
 <div className="score-breakdown"><div><span>Automatic marking</span><strong>{r.automatic}<small>/ 50</small></strong></div><div><span>Written marking</span><strong>{r.written}<small>/ 50 {r.pending?"so far":""}</small></strong></div><div><span>Overall score</span><strong>{r.total===null?"Pending":r.total+" / 100"}</strong></div></div></div>
 <div className="result-footnote"><WarningCircle size={17}/><p>{r.pending?r.pending+" written answers need review. They are excluded from an overall grade until reviewed.":"Written marks use self-review. This report is a practice record, not an institution-verified result."} Blank answers receive zero marks.</p></div></section>
 {r.pending>0&&<a href="#answer-review" className="review-callout no-print" onClick={()=>{setFilter("pending");setSection("all")}}><BookOpen size={24}/><div><strong>Complete your written review</strong><span>Compare each answer with the model answer and award marks using the rubric.</span></div><ArrowRight size={22}/></a>}
 <div className="report-analysis"><section className="section-results"><h2>Section by section.</h2><div className="results-table">{r.sections.map(s=><div className="result-row" key={s.code}><span className="section-letter">{s.code}</span><div><strong>{s.title}</strong><div className="thin-bar"><span style={{width:s.score/s.max*100+"%"}}/></div></div><div><strong className="mono">{s.score} / {s.max}</strong><small>{s.pending?s.pending+" pending":s.code<"E"?"Automatic":"Self-reviewed"}</small></div></div>)}</div></section>
 <section className="topic-results"><Target size={29}/><h2>Where to focus next.</h2>{weak.length?<p>Start with <strong>{weak[0].topic.toLowerCase()}</strong>, your lowest fully reviewed topic.</p>:<p>{r.pending?"Complete the written review for a full picture of your strengths.":"You earned full marks across the assessed topics. Keep practising your explanations."}</p>}
 {r.topics.map(t=><div className="topic-score" key={t.topic}><div><span>{t.topic}</span><strong>{t.score}/{t.max}{t.pending?" *":""}</strong></div><div className="thin-bar"><span style={{width:t.score/t.max*100+"%"}}/></div></div>)}{r.pending>0&&<small className="muted">* Incomplete while written marks are pending.</small>}
 <div className="grade-key"><strong>Grading guide</strong><span>A+ 90+ · A 80+ · B 70+ · C 60+ · D 50+</span><small>Pass threshold: 50 / 100</small></div></section></div>
 <section className="reflection-summary"><div><h2>Understand the mistake.</h2><p>Use A-E in each answer review to record why you missed it.</p></div><div className="reflection-grid">{Object.entries(REFLECTIONS).map(([key,label])=><div key={key}><span>{key}</span><strong>{Object.values(data.answers).filter(a=>a.reflection===key).length}</strong><p>{label}</p></div>)}</div></section>
 <section id="answer-review" className="answer-review"><div className="review-heading"><div><h2>Review the reasoning.</h2><p>Accepted equivalents are noted in the model answers. Written marks are your own assessment.</p></div><div className="review-filters no-print"><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All answers</option><option value="missed">Marks missed</option><option value="pending">Written review pending</option><option value="flagged">Flagged questions</option></select></label><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option value="all">All sections</option>{SECTION_DEFINITIONS.map(s=><option key={s.code} value={s.code}>{s.code}. {s.title}</option>)}</select></label></div></div>
 <p className="small muted">{reviewQuestions.length} questions shown</p>{reviewQuestions.length===0&&<div className="empty-review"><CheckCircle size={30}/><p>No questions match this filter.</p></div>}
 {reviewQuestions.map(q=>{const answer=data.answers[q.id],feedback=data.feedback![q.id];return <details key={q.id} className="review-item"><summary><span className="mono">Q{String(q.id).padStart(2,"0")}</span><strong>{q.prompt}</strong><span className={feedback.mark===null?"mark-pending":feedback.mark===q.points?"mark-correct":"mark-missed"}>{feedback.mark===null?"Pending":feedback.mark+" / "+q.points}</span></summary><div className="review-content">{q.code&&<pre className="sql-code">{q.code}</pre>}<div className="answer-comparison"><div><h3>Your answer</h3><pre>{answerText(q,answer?.value??"")}</pre>{answer?.correction&&<><h4>Your correction</h4><p>{answer.correction}</p></>}</div><div><h3>{q.kind==="written"?"Model answer":"Correct answer"}</h3><pre>{feedback.model}</pre>{q.kind!=="written"&&<p>{feedback.explanation}</p>}</div></div>
 {q.kind==="written"&&<div className="rubric"><h3>Marking guide</h3><ul>{feedback.rubric.map(item=><li key={item}>{item}</li>)}</ul>{answer?.value.trim()?<label>Self-review mark <select disabled={busy} value={answer.reviewMark??""} onChange={e=>{if(e.target.value!=="")void update({action:"review",id:a.id,marks:[{id:q.id,mark:Number(e.target.value)}]})}}><option value="">Choose a mark</option>{Array.from({length:q.points+1},(_,i)=><option key={i} value={i}>{i} / {q.points}</option>)}</select></label>:<p className="small">Unanswered: 0 marks. No review is needed.</p>}<p className="small muted">Each rubric item is worth 1 mark. This is self-review, not verified teacher grading.</p></div>}
 <label className="reflection-select">What explains this result?<select disabled={busy} value={answer?.reflection??""} onChange={e=>void update({action:"reflect",id:a.id,qid:q.id,reason:e.target.value})}><option value="">Choose a reflection (optional)</option>{Object.entries(REFLECTIONS).map(([key,label])=><option key={key} value={key}>{key}. {label}</option>)}</select></label>
 </div></details>})}</section>
 <section className="next-attempt no-print"><div><h2>A clearer next attempt.</h2><p>Review the concepts you missed, then come back and try again.</p></div><a href="/#begin"><ArrowCounterClockwise size={20}/>Retake exam</a></section>
 <div className="sources-note"><h3>Reference notes</h3><p>MySQL 8.4 documentation: <a href="https://dev.mysql.com/doc/refman/8.4/en/data-types.html" target="_blank" rel="noreferrer">Data types</a> · <a href="https://dev.mysql.com/doc/refman/8.4/en/delete.html" target="_blank" rel="noreferrer">DELETE</a> · <a href="https://dev.mysql.com/doc/refman/8.4/en/truncate-table.html" target="_blank" rel="noreferrer">TRUNCATE</a> · <a href="https://dev.mysql.com/doc/refman/8.4/en/spatial-type-overview.html" target="_blank" rel="noreferrer">Spatial types</a></p><small>Attempt ID: {a.id}</small></div>
 </>}
 </>}
 </main></Shell>
}
